apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app : capstone-app  
    spec:
      containers:
        - name: capstone-app
          image:   211825533736.dkr.ecr.us-west-2.amazonaws.com/eks-capstone-cluster:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80