apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: capstone-app-service  
  name: service-name-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: capstone-app-service 
    port: 80
    protocol: TCP
  selector:
    app: capstone-app